//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3053
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("XBMC Touch")]
[assembly: AssemblyCompany("Danone-KiD")]
[assembly: AssemblyProduct("XBMC Touch")]
[assembly: AssemblyCopyright("Copyright Danone-KiD© 2009")]
[assembly: ComVisible(false)]
[assembly: Guid("88812638-9547-4480-9bf4-4fe25103b35c")]
[assembly: AssemblyVersion("1.0.56.26")]
[assembly: AssemblyFileVersion("1.0.56.26")]


